//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buoi4_Demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyThanhVienEntities : DbContext
    {
        public QuanLyThanhVienEntities()
            : base("name=QuanLyThanhVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoaiThanhVien> LoaiThanhViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThanhVien> ThanhViens { get; set; }
        public virtual DbSet<View_NguoiDung> View_NguoiDung { get; set; }
        public virtual DbSet<View_ThongTinThanhVien> View_ThongTinThanhVien { get; set; }
    
        public virtual int usp_Sua_ThanhVien(string taiKhoan, string matKhau, string hoTen, string email, string diaChi, string soDienThoai, Nullable<int> maLoaiThanhVien)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var maLoaiThanhVienParameter = maLoaiThanhVien.HasValue ?
                new ObjectParameter("MaLoaiThanhVien", maLoaiThanhVien) :
                new ObjectParameter("MaLoaiThanhVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Sua_ThanhVien", taiKhoanParameter, matKhauParameter, hoTenParameter, emailParameter, diaChiParameter, soDienThoaiParameter, maLoaiThanhVienParameter);
        }
    
        public virtual int usp_Them_ThanhVien(string taiKhoan, string matKhau, string hoTen, string email, string diaChi, string soDienThoai, Nullable<int> maLoaiThanhVien)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var maLoaiThanhVienParameter = maLoaiThanhVien.HasValue ?
                new ObjectParameter("MaLoaiThanhVien", maLoaiThanhVien) :
                new ObjectParameter("MaLoaiThanhVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Them_ThanhVien", taiKhoanParameter, matKhauParameter, hoTenParameter, emailParameter, diaChiParameter, soDienThoaiParameter, maLoaiThanhVienParameter);
        }
    
        public virtual ObjectResult<usp_Tim_ThanhVien_TheoLoai_Result> usp_Tim_ThanhVien_TheoLoai(Nullable<int> maLoaiThanhVien)
        {
            var maLoaiThanhVienParameter = maLoaiThanhVien.HasValue ?
                new ObjectParameter("MaLoaiThanhVien", maLoaiThanhVien) :
                new ObjectParameter("MaLoaiThanhVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Tim_ThanhVien_TheoLoai_Result>("usp_Tim_ThanhVien_TheoLoai", maLoaiThanhVienParameter);
        }
    
        public virtual int usp_Xoa_ThanhVien(string taiKhoan)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Xoa_ThanhVien", taiKhoanParameter);
        }
    
        public virtual ObjectResult<ThanhVien> usp_Tim_ThanhVien_TheoTen(string hoTen)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThanhVien>("usp_Tim_ThanhVien_TheoTen", hoTenParameter);
        }
    
        public virtual ObjectResult<ThanhVien> usp_Tim_ThanhVien_TheoTen(string hoTen, MergeOption mergeOption)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThanhVien>("usp_Tim_ThanhVien_TheoTen", mergeOption, hoTenParameter);
        }
    }
}
