//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buoi4_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhVien
    {
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<int> MaLoaiThanhVien { get; set; }
    
        public virtual LoaiThanhVien LoaiThanhVien { get; set; }
    }
}
